# Creating Quarto Book
# https://quarto.org/docs/books/
#
# options for Quarto book
# https://quarto.org/docs/reference/projects/books.html
#
# Options for html
# https://quarto.org/docs/reference/projects/websites.html#section

project:
  type: book
  output-dir: docs
  # resources:  # in case something was not included in rendered site automatically
  #   - "data/*"
  #   - "images/*"



number-depth: 2



book:
  title: "COMP/STAT212 Portfolio"
  author: "Yeshe Jangchup"
  date: today  # use today to update date published based on last time project was edited
  date-format: full
  # favicon: path/to/favorite-logo.png
  reader-mode: true
  # site-url: https://site-url
  page-navigation: true
  back-to-top-navigation: true
  cookie-consent:
    type: implied
    style: simple
  # bread-crumbs: true  # causes problems with older Quarto version
  # downloads: [pdf]
  # repo-url: https://repo-url
  # repo-actions: [edit, issue]
  # repo-link-target: "_blank" #makes issue and edit links open in a new window/tab

  # page-footer:
    # background: "dark"
    # left: |
      # footer text

  sidebar:
    title: "Yeshe Jangchup"
    logo: assets/sidebar-logo.png
    logo-alt: "Random negative space illustration"
    collapse-level: 2
    style: "docked"
    pinned: true
    search: true
    # tools:
    #   - icon: "filetype-doc"
    #     href: "https://link-to-tool"

  chapters:
    - text: "Welcome"
      href: index.qmd

    - part: "Homework"
      chapters:
      - homework-yeshedj/hw01/src/hw1-tt.qmd
      - homework-yeshedj/hw02/src/hw02-p1.qmd
      - homework-yeshedj/hw02/src/hw02-p2.qmd
      - homework-yeshedj/hw03/src/hw03-p1.qmd
      - homework-yeshedj/hw03/src/hw03-p2.qmd
      - homework-yeshedj/hw04/src/hw04-p1.qmd
      - homework-yeshedj/hw05/src/hw05-p1.qmd
      - homework-yeshedj/hw05/src/hw05-p2.qmd
      - homework-yeshedj/hw06/src/hw06.qmd
      - homework-yeshedj/hw07/src/hw07-p1.qmd
      - homework-yeshedj/hw07/src/hw07-p2.qmd
      - homework-yeshedj/hw08/src/hw08-p1.qmd
      - homework-yeshedj/hw08/src/hw08-p2.qmd




    - part: "TidyTuesday"
      chapters:
      - homework-yeshedj/hw01/src/hw1-tt.qmd
      - tt/2025-07-15.qmd

    - part: "Pre-Class Learnings"
      chapters:
      - pcl/1_pcl.Rmd
      - pcl/2_pcl.Rmd
      - pcl/3_pcl.Rmd
      - pcl/4_pcl.Rmd
      - pcl/6_pcl.Rmd
      - pcl/7_pcl.Rmd
      - pcl/8_pcl.Rmd
      - pcl/9_pcl.Rmd
      - pcl/10_pcl.Rmd
      - pcl/11_pcl.Rmd
      - pcl/12_pcl.Rmd
      - pcl/13_pcl.Rmd
      - pcl/14_pcl.Rmd
      - pcl/15_pcl.Rmd
      - pcl/16_pcl.Rmd
      - pcl/17_pcl.Rmd
      - pcl/18_pcl.Rmd



    - part: "In-Class Activities"
      chapters:
      - ica/02_review/cleaning.qmd
      - ica/03_adv_ggplot/code/03-adv-ggplot-notes.qmd
      - ica/04_adv_maps/code/04-adv-maps-1-notes.qmd
      - ica/06_adv_data_wrangling1/06-wrangling-1-notes.qmd
      - ica/07_adv_data_wrangling2/07-wrangling-2-notes.qmd
      - ica/08_missing_data/08-missing-data-notes.qmd
      - ica/09_functions/09-functions-notes.qmd
      - ica/10_base_r/10-base-r-notes.qmd
      - ica/11_loops_and_Iter_1/11-iteration-1-notes.qmd
      - ica/12_loops_and_iter_2/12-iteration-2-notes.qmd
      - ica/14_apis_2/14-apis-2-notes.qmd
      - ica/15_web_scraping/15-scraping-notes.qmd
      - ica/16_databases_and_sql/16-databases-notes.qmd
      - ica/18_interactive_viz/18-interactive-viz-notes.qmd



    - part: "Extras"
      chapters:
      - extra/extra-sample2.qmd



format:
  html:
    theme: # bootswatch themes--other options https://bootswatch.com/
      light: flatly
      dark: darkly
    search: true
    toc: true
    toc-depth: 3
    link-external-newwindow: true
    css: style/custom.css
    fontsize: 1em
    smooth-scroll: true
    code-overflow: scroll
    code-copy: true
    code-link: true
    code-line-numbers: true
    code-block-bg: true
    code-block-border-left: "#1482FA"
    code-tools: true
    page-layout: full
    code-fold: true
    number-sections: false
    toc-expand: true
    # grid:
    #   sidebar-width: 200px
    #   body-width: 950px
    #   margin-width: 150px

  # pdf:
  #   documentclass: scrreprt
  #   keep-tex: false



execute:
  echo: true
  warning: false
  error: false
  cache: false
#   freeze: auto # remove when using GitHub action to execute code



editor:
  mode: source
  markdown:
    wrap: sentence # Forces each sentence to be on its own line in source markdown, however, it doesn't affect how it is rendered
